"""init

Revision ID: fdae7033662e
Revises: 
Create Date: 2020-11-10 11:24:10.059882

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fdae7033662e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lecture',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('lecture_name', sa.String(), nullable=False),
    sa.Column('professor_name', sa.String(), nullable=False),
    sa.Column('lecture_time', sa.String(), nullable=False),
    sa.Column('limited_people', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('pw', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('basket',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('lecture_id', sa.Integer(), nullable=True),
    sa.Column('is_valid', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['lecture_id'], ['lecture.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('basket')
    op.drop_table('user')
    op.drop_table('lecture')
    # ### end Alembic commands ###
